[package]
name = "zksync_os_sys"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_os_interface.workspace = true
alloy = { workspace = true, default-features = false }
anyhow.workspace = true
bincode.workspace = true
libloading = "0.8"
