services:
  ci-runner:
    image: "ghcr.io/matter-labs/zk-environment:latest2.0-lightweight"
    security_opt:
      - seccomp:unconfined
    command: tail -f /dev/null
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ..:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    extra_hosts:
      - "host:host-gateway"
    network_mode: host
