#!/usr/bin/env bash

set -o errexit
set -o pipefail

# Needs following configuration
# URL - URL of the API endpoint
# INTERVAL - Time interval for polling in seconds
# TIMEOUT - Timeout of script in seconds
# LAST_BATCH_NUMBER - Last number of the batch to check

# Start timer
START_TIME=$(date +%s)

echo "URL: $URL"

for ((BATCH_NUMBER=1; BATCH_NUMBER<=$LAST_BATCH_NUMBER; BATCH_NUMBER++)); do
  # Loop to query periodically
  while true; do
      # Calculate the elapsed time
      CURRENT_TIME=$(date +%s)
      ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

      # Check if the timeout has been reached
      if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
          echo "Timeout reached. Failing CI..."
          exit 1  # Exit with non-zero status to fail CI
      fi

      # Run the curl request and capture the response
      HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL/prover-jobs/FRI/$BATCH_NUMBER")

      # Check if the status code is 200
      if [ "$HTTP_CODE" -eq 200 ]; then
          echo "Received 200 OK response for batch $BATCH_NUMBER"
          break
      else
          echo "Received HTTP status $HTTP_CODE, retrying in $INTERVAL seconds..."
          sleep $INTERVAL
      fi
  done
done
