version: "3.9"

services:
  sequencer:
    build: .               # or `image: ghcr.io/you/zksync-os:latest`
    container_name: sequencer
    restart: unless-stopped
    environment:
      RUST_LOG: info
      # add your own env vars here
    volumes:
      - sequencer-db:/data       # SSD-backed volume
    ports:
      - "3000:3000"              # JSON-RPC
      - "3124:3124"              # prover-api
      - "3312:3312"              # Prometheus metrics
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3312/metrics || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:10.4.1
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: changeme
    volumes:
      - grafana-data:/var/lib/grafana
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3001:3000"   # host-side 3001 → Grafana 3000

volumes:
  sequencer-db: {}
  prometheus-data: {}
  grafana-data: {}
