{
 "title": "zksync-os-sequencer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Proving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proving time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(prover_prove_time_seconds_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proving time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prover_prove_time_seconds_sum[$__rate_interval]) / rate(prover_prove_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batcher (Prover Input Generator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "prover input generation - total",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(batcher_prover_input_generation_seconds_bucket{stage=\"prover_input_generation\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prover input generation - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(batcher_prover_input_generation_seconds_sum{stage=\"prover_input_generation\"}[$__rate_interval]) / rate(batcher_prover_input_generation_seconds_count{stage=\"prover_input_generation\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "average block processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tree_block_time_seconds_sum[$__rate_interval]) / rate(tree_block_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "block processing in tree",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(tree_block_time_seconds_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average entry processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tree_entry_time_seconds_sum[$__rate_interval]) / rate(tree_entry_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "entry processing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(tree_entry_time_seconds_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tree Range size ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(tree_processing_range_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "current block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "sealed_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "one tx (vm+storage) exec time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(block_execution_stages_seconds_sum{stage=\"execute\"}[$__rate_interval]) / rate(block_execution_stages_seconds_count{stage=\"execute\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(executed_transactions[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exec - exec tx",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(block_execution_stages_seconds_bucket{stage=\"execute\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "amound spent on (execution + storage) per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(block_execution_stages_seconds_sum{stage=\"execute\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(block_execution_stages_seconds_sum{stage=\"wait_for_tx\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(storage_view_access_seconds_sum{stage=\"total\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(preimage_access_latency_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exec - wait for tx",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "rate(block_execution_stages_seconds_bucket{stage=\"wait_for_tx\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Replay Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 539 },
     "targets": [
      {
       "expr": "rate(block_replay_storage_get_latency_seconds_bucket[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "send raw transaction latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 540 },
     "targets": [
      {
       "expr": "rate(response_time_seconds_bucket{method=\"send_raw_transaction\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "estimate gas latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 540 },
     "targets": [
      {
       "expr": "rate(response_time_seconds_bucket{method=\"estimate_gas\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "call latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 548 },
     "targets": [
      {
       "expr": "rate(response_time_seconds_bucket{method=\"call\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Mempool size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(mempool_len_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Preimages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Preimage get",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_bucket{stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage set",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "rate(preimages_set_seconds_bucket{stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage get avvg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_sum[$__rate_interval]) / rate(preimages_get_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage set avvg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(preimages_set_seconds_sum[$__rate_interval]) / rate(preimages_set_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Preimage get count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(preimages_get_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "State persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compact latency per block - avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(storage_map_rocks_db_compact_seconds_sum[$__rate_interval]) / rate(storage_map_rocks_db_compact_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compact latency per block",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(storage_map_rocks_db_compact_seconds_bucket[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "One block state persist ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(storage_add_diff_seconds_sum{stage=\"total\"}[$__rate_interval]) / rate(storage_add_diff_seconds_count{stage=\"total\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Storage View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "storage access total avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(storage_view_access_seconds_sum{stage=\"total\"}[$__rate_interval]) / rate(storage_view_access_seconds_count{stage=\"total\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage access - diffs vs base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "rate(storage_view_access_seconds_count{stage=\"base\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(storage_view_access_seconds_count{stage=\"total\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Access time - total",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "rate(storage_view_access_seconds_bucket{stage=\"total\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Access time - base",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 98 },
   "targets": [
    {
     "expr": "rate(storage_view_access_seconds_bucket{stage=\"base\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Access time - diffs",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "rate(storage_access_latency_seconds_bucket{stage=\"diff\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Access - diffs scanned",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "rate(storage_view_diffs_scanned_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Access - diffs scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(storage_view_diffs_scanned_sum[$__rate_interval]) / rate(storage_view_diffs_scanned_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}