[package]
name = "zksync_os_l1_consistency_checker"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_os_contract_interface.workspace = true
zksync_os_observability.workspace = true
zksync_os_pipeline.workspace = true
zksync_os_types.workspace = true
zksync_os_batch_types.workspace = true
zksync_os_interface.workspace = true
zksync_os_merkle_tree.workspace = true
zksync_os_multivm.workspace = true
zksync_os_storage_api.workspace = true

anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
