name: Security audit

on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    # Run every Monday-Friday at 8:30 AM UTC.
    - cron: "30 8 * * 1-5"

# Prevent multiple runs for the same pull request or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Set permissions
permissions:
  contents: read
  issues: write # required for cargo-audit
  checks: write # required for cargo-audit

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      # Pre-install cargo-audit to avoid using nightly toolchain after checking out code
      - name: Install cargo-audit
        run: cargo install --locked cargo-audit@0.21.2
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run cargo audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # todo - remove after `tracing-subscriber` is `>=0.3.20` in all dependencies
          ignore: 'RUSTSEC-2025-0055'

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@f2ba7abc2abebaf185c833c3961145a3c275caad # v2.0.13
        with:
          manifest-path: "./Cargo.toml"
          command: check
          command-arguments: "--allow unmaintained --hide-inclusion-graph"
