name: Docker build and release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag of an image to build."
        type: string
        required: true
  push:
    branches:
      - main
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: 'bash -ex {0}'

jobs:

  build-images:
    name: Build and Push Docker Images
    runs-on: matterlabs-ci-runner-high-performance
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        component:
          - zksync-os-server

    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: login to Docker registries
        run: gcloud auth configure-docker us-docker.pkg.dev -q

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 7
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.component }}
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/${{ matrix.component }}
          tags: |
            type=raw,value=${{ inputs.tag_name }},enable=${{ inputs.tag_name != '' }}
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=sha,format=short,prefix=,suffix=-{{date 'x'}},enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=ref,event=pr

      - name: Define whether to save cache
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: set-cache-to
        run: echo "cache-to=type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.component }}:buildcache,mode=max" >> "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          load: true
          file: ./Dockerfile
          build-args: |
            SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
            SCCACHE_GCS_SERVICE_ACCOUNT=gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com
            SCCACHE_GCS_RW_MODE=READ_WRITE
            RUSTC_WRAPPER=sccache
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: 'type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.component }}:buildcache'
          cache-to: ${{ steps.set-cache-to.outputs.cache-to }}
