//! Promotes observers into the committee, live — the rig-side execution of the
//! promotion runbook (docs/src/consensus/enabling.md, "Promoting an observer"):
//!
//! 1. append a schedule entry (activation epoch from `--activation-epoch`, or
//!    "current + margin" read from the chain) seating the next `--candidates`
//!    observers;
//! 2. regenerate every node's overlay from the work directory's materials —
//!    sitting validators get the new schedule and lose the candidates from their
//!    admission lists; candidates flip to `role: validator` and gain their
//!    (pre-minted) BLS keys;
//! 3. rolling `docker restart`, sitting committee first, candidates last, each
//!    gated on the node's `/status` coming back healthy;
//! 4. rewrite the manifest: candidates move into `validators`, `quorum` grows —
//!    so a `chaos drive` started afterwards reasons about the promoted committee.
//!
//! Deliberately promote-then-drive: faults *during* the promotion window would
//! need the driver to reason about a committee whose size is changing mid-run —
//! a follow-up, not this tool. Run the fault schedule after this exits.

use crate::setup::{Manifest, Materials, ScheduleStep, node_overlay};
use anyhow::Context as _;
use clap::Args;
use std::path::PathBuf;
use std::time::Duration;

#[derive(Args)]
pub struct PromoteArgs {
    /// Work directory produced by `chaos setup` (with a running cluster).
    #[arg(long)]
    pub workdir: PathBuf,
    /// How many observers to promote (the next ones in index order).
    #[arg(long, default_value_t = 1)]
    pub candidates: usize,
    /// The epoch the grown committee activates at. Defaults to the chain's
    /// current epoch plus a margin that comfortably covers the rolling restarts.
    #[arg(long)]
    pub activation_epoch: Option<u64>,
    /// Margin (in epochs) over the current epoch when `--activation-epoch` is
    /// not given.
    #[arg(long, default_value_t = 4)]
    pub margin: u64,
}

pub async fn run(args: PromoteArgs) -> anyhow::Result<()> {
    let manifest_path = args.workdir.join("manifest.json");
    let materials_path = args.workdir.join("materials.json");
    let mut manifest: Manifest = serde_json::from_str(&std::fs::read_to_string(&manifest_path)?)
        .context("unreadable manifest.json")?;
    let mut materials: Materials = serde_json::from_str(&std::fs::read_to_string(&materials_path)?)
        .context(
            "unreadable materials.json (generated by `chaos setup` — old work \
             directories predate promotion support)",
        )?;

    let sitting = materials.scheduled_validators();
    let total = materials.nodes.len();
    anyhow::ensure!(args.candidates > 0, "nothing to promote");
    anyhow::ensure!(
        sitting + args.candidates <= total,
        "the cluster has {} unpromoted observers, {} requested",
        total - sitting,
        args.candidates,
    );

    // The activation epoch: everyone's configs must name the same one, so decide
    // it up front — from the chain when not given. (If the restarts overran it,
    // the committee would run short until the candidates arrive; late first
    // engines are safe. The margin keeps the handoff clean.)
    let activation_epoch = match args.activation_epoch {
        Some(epoch) => epoch,
        None => {
            let height = current_height(&manifest).await?;
            height / materials.epoch_length + args.margin
        }
    };
    let last = materials
        .schedule
        .last()
        .expect("schedule has its epoch-0 entry");
    anyhow::ensure!(
        activation_epoch > last.activation_epoch,
        "activation epoch {activation_epoch} does not follow the schedule's last \
         entry ({})",
        last.activation_epoch,
    );

    // Step 1+2: the new materials, and every node's regenerated overlay.
    materials.schedule.push(ScheduleStep {
        activation_epoch,
        validators: sitting + args.candidates,
    });
    for index in 0..total {
        let overlay = node_overlay(&materials, index);
        std::fs::write(
            args.workdir
                .join(format!("validator-{index}/validator.yaml")),
            overlay,
        )?;
    }
    std::fs::write(&materials_path, serde_json::to_string_pretty(&materials)?)?;

    // Step 3: rolling restarts — sitting committee first (they must know the new
    // schedule before the boundary), candidates last (flipping roles).
    for index in 0..sitting + args.candidates {
        let entry = if index < sitting {
            &manifest.validators[index]
        } else {
            &manifest.observers[index - sitting]
        };
        let name = format!("chaos-{}", entry.name);
        println!("restarting {name} with the promoted configuration");
        let status = tokio::process::Command::new("docker")
            .args(["restart", &name])
            .status()
            .await
            .context("docker restart")?;
        anyhow::ensure!(status.success(), "docker restart {name} failed");
        wait_healthy(entry.host_status_port).await?;
    }

    // Step 4: the manifest a subsequent `chaos drive` reads — candidates are
    // committee members now, and quorum arithmetic follows the grown size.
    let promoted: Vec<_> = manifest.observers.drain(..args.candidates).collect();
    manifest.validators.extend(promoted);
    let n = manifest.validators.len();
    manifest.quorum = n - (n - 1) / 3;
    std::fs::write(&manifest_path, serde_json::to_string_pretty(&manifest)?)?;

    println!(
        "promoted {} observer(s); the committee of {n} (quorum {}) activates at \
         epoch {activation_epoch} — drive faults or load whenever you like",
        args.candidates, manifest.quorum,
    );
    Ok(())
}

/// The highest height any reachable committee member serves.
async fn current_height(manifest: &Manifest) -> anyhow::Result<u64> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(3))
        .build()?;
    let mut best = None;
    for entry in &manifest.validators {
        let response: Result<serde_json::Value, _> = async {
            client
                .post(format!("http://127.0.0.1:{}", entry.host_rpc_port))
                .json(&serde_json::json!({
                    "jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []
                }))
                .send()
                .await?
                .json()
                .await
        }
        .await;
        if let Ok(value) = response
            && let Some(hex) = value.get("result").and_then(|result| result.as_str())
            && let Ok(height) = u64::from_str_radix(hex.trim_start_matches("0x"), 16)
        {
            best = Some(best.unwrap_or(0).max(height));
        }
    }
    best.context("no committee member answered eth_blockNumber — is the cluster up?")
}

/// Polls a node's `/status` until it reports healthy (or times out) — the gate
/// between rolling restarts.
async fn wait_healthy(status_port: u16) -> anyhow::Result<()> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()?;
    let deadline = std::time::Instant::now() + Duration::from_secs(120);
    loop {
        let healthy = async {
            let value: serde_json::Value = client
                .get(format!("http://127.0.0.1:{status_port}/status"))
                .send()
                .await?
                .json()
                .await?;
            anyhow::Ok(value.get("healthy").and_then(|h| h.as_bool()) == Some(true))
        }
        .await
        .unwrap_or(false);
        if healthy {
            return Ok(());
        }
        anyhow::ensure!(
            std::time::Instant::now() < deadline,
            "node on status port {status_port} did not come back healthy within 120s"
        );
        tokio::time::sleep(Duration::from_secs(2)).await;
    }
}
