name: Build images
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN_:
        description: "Github token to push images to ghcr"
        required: true
      GH_TOKEN:
        description: "Token for cloning private repositories"
        required: true
    inputs:
      IMAGE_TAG:
        description: "Image tag name"
        type: string
        required: true

jobs:
  build-images:
    name: Build and Push Docker Images
    env:
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    runs-on: [matterlabs-ci-runner-high-performance]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        components:
          - zksync-os-server

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: login to Docker registries
        shell: bash
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN_ }}

      - name: Build docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          load: true
          file: ./Dockerfile
          build-args: |
            SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
            SCCACHE_GCS_SERVICE_ACCOUNT=gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com
            SCCACHE_GCS_RW_MODE=READ_WRITE
            RUSTC_WRAPPER=sccache
          tags: |
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/${{ matrix.components }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.components }}:${{ env.IMAGE_TAG }}

      - name: Push docker image
        run: |
          docker push us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/${{ matrix.components }}:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.components }}:${{ env.IMAGE_TAG }}
