name: Security audit
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    # Run every Monday-Friday at 8:30 AM UTC.
    - cron: "30 8 * * 1-5"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # todo - remove after `tracing-subscriber` is `>=0.3.20` in all dependencies
          ignore: 'RUSTSEC-2025-0055'
