name: Release-please

# Give permissions to the release-please to open, update PRs
# and commit to PRs the repository to update Cargo.lock
permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  issues: write # required for release-please labels

# Run the workflow on push to the main branch or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Prepare the release PR with changelog updates and create github releases
  release-please:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@v1 # use v1 to get bugfixes here instead of SHA
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}     # Slack webhook for release notifications
      gh_token: ${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }} # GitHub token for releases generation
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}     # Token for publishing to crates.io
    with:
      config: '.github/release-please/config.json'          # Path to the configuration file
      manifest: '.github/release-please/manifest.json'      # Path to the manifest file
      update-cargo-lock: true                               # Update Cargo.lock file in the release PR
      publish-to-crates-io: false                           # Enable publishing to crates.io
      version-suffix: 'non-semver-compat'                   # Version suffix for the crates.io release
      dependencies: 'clang libclang-dev'                    # Additional Linux dependencies to install
